---
title: Оператори Python
hero_image: images/banner.png
description: У цій статті пояснюються основні принципи використання операторів у Ptyhon 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Оператори Python
