---
title: Python operatoren
hero_image: images/banner.png
description: Ingrediënt dat de basis uitlegt van het gebruik van operatoren in Python 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Python operatoren
