---
title: Gweithredwyr Python
hero_image: images/banner.png
description: Elfen yn esbonio hanfodion defnyddio gweithredwyr yn Python 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Gweithredwyr Python
