---
title: Operadores no Python
hero_image: images/banner.png
description: Tutorial explicando os fundamentos do uso de operadores no Ptyhon 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Operadores no Python
