---
title: Operadores de Python
hero_image: images/banner.png
description: Ingrediente que explica los conceptos básicos del uso de operadores en Python 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Operadores de Python
