---
title: Python operators
hero_image: images/banner.png
description: Ingredient explaining the basics of using operators in Ptyhon 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - 
    title: Python operators
