---
title: Opérateurs Python
hero_image: images/banner.png
description: Ingrédient expliquant les bases de l'utilisation des opérateurs dans Ptyhon 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Opérateurs Python
