---
title: Operatori Python
hero_image: images/banner.png
description: Pillola che spiega le basi dell'uso degli operatori in Python 3
version: 4
listed: false
copyedit: false
last_tested: "2021-08-11"
steps:
  - title: Operatori Python
